name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ec2-51-20-98-111.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/presentation-dashboard"
        recursive: true
        exclude: |
          node_modules
          frontend/node_modules
          .env

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ec2-51-20-98-111.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/presentation-dashboard
          npm run build
          sudo systemctl restart myapp.service